---
- name: Install FRR
  package:
    name:
      - frr
      - python-ipaddress
      - frr-pythontools
    state: latest  # noqa 403
  become: true
  notify:
    - restart frr

- name: ubuntu | Touch FRR reload log
  file:
    path: /var/log/frr/frr-reload.log
    state: touch
    owner: frr
    group: frr
    mode: 0644
    modification_time: preserve
    access_time: preserve
  become: true
