---
# handlers file for ansible-frr
- name: full restart frr
  service:
    name: frr
    state: restarted
    enabled: true
  become: true
  listen: "restart frr"

- name: reload frr
  service:
    name: frr
    state: reloaded
    enabled: true
  become: true
  listen: "reload frr"

- name: start frr
  service:
    name: frr
    state: started
    enabled: true
  become: true
  listen: "start frr"

## Quagga restart
- name: full restart quagga
  service:
    name: quagga
    state: restarted
    enabled: true
  become: true
  listen: "restart quagga"

- name: reload quagga
  service:
    name: quagga
    state: reloaded
    enabled: true
  become: true
  listen: "reload quagga"

- name: start quagga
  service:
    name: quagga
    state: started
    enabled: true
  become: true
  listen: "start quagga"
